{% set name = "kepderiv" %}
{% set version = "1.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kepderiv-{{ version }}.tar.gz
  sha256: 1859aa85fa2f8fb0ca7b8b16ff6a47a98824f0f28f1de2cdfbc24393f759ca91

build:
  number: 1
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - numpy >=1.16
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - kepderiv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.unige.ch/jean-baptiste.delisle/kepderiv
  summary: Keplerian modeling and derivatives for radial velocities analysis.
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - jbdelisle
