{% set name = "kepderiv" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kepderiv-{{ version }}.tar.gz
  sha256: 8239bf376a8b30b2e989fb5f0418cf2b06411ea80c39cc7959f213a4008b9e3a

build:
  number: 1
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - numpy >=1.16
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - kepderiv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.unige.ch/jean-baptiste.delisle/kepderiv
  summary: Keplerian modeling and derivatives for radial velocities analysis.
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - jbdelisle
